id: hl7.fhir.uv.fall-risk
canonical: https://example.org/fhir/fall-risk
name: FallRiskAssessmentIG
title: "Fall Risk Assessment Implementation Guide"
description: "Interoperable FHIR-based fall risk assessment for older adults using standardized scoring, objective performance tests, and EHR-derived data."
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: ci-build
license: CC0-1.0
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001 "World"

publisher:
  name: Fall Risk IG Authors
  url: https://example.org/fall-risk
  email: info@example.org



pages:
  index.md:
    title: Home
  usecase.md:
    title: Use Case
  architecture.md:
    title: Architecture
  dataflow.md:
    title: Data Flow & Scoring
  examples.md:
    title: Examples

menu:
  Home: index.html
  Use Case: usecase.html
  Architecture: architecture.html
  Data Flow & Scoring: dataflow.html
  Examples: examples.html
  Artifacts: artifacts.html

parameters:
  show-inherited-invariants: false
  path-resource:
    - input/examples
  path-pages:
    - input/pagecontent

FSHOnly: false
applyExtensionMetadataToRoot: false
instanceOptions:
  setMetaProfile: always
  setId: always
  manualSliceOrdering: false
